name: Get latest patches release version
on:
  schedule:
    - cron:  '25 */12 * * *'
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # repository: 'jarnedemeulemeester/findroid'
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch sha 
        run: |
          curl -sL https://api.github.com/repos/jarnedemeulemeester/findroid/branches/main | \
          jq -r ".commit.sha" > commits/sha-latest.md 
      - name: Fetch commit message
        run: |
          curl -sL https://api.github.com/repos/jarnedemeulemeester/findroid/branches/main | \
          jq  -r ".commit.commit.message" > commits/commit-latest.md
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Check for type of commit
        id: commit-check
        run: echo "translation=$([ -z "`[[ $(cat commits/commit-latest.md) == *translat* ]] && echo matched`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true' && steps.commit-check.outputs.translation =='false'
        run: |
          git config --global user.name 'Findroid-Creator'
          git config --global user.email 'Findroid-Creator@users.noreply.github.com'
          git commit -am "New commits released, starting CI"
          git push
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 4