name: Publish release APK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
#     tags:
#       - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v3
        with:
          repository: 'jarnedemeulemeester/findroid'
      
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate signed APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ./app/phone/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_STORE }}
          alias: ${{ secrets.KEY_STORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./app/phone/build/outputs/apk/release/phone-universal-release-unsigned-signed.apk
            ./app/phone/build/outputs/apk/release/phone-arm64-v8a-release-unsigned-signed.apk
            ./app/phone/build/outputs/apk/release/phone-armeabi-v7a-release-unsigned-signed.apk
            ./app/phone/build/outputs/apk/release/phone-x86_64-release-unsigned-signed.apk
            ./app/phone/build/outputs/apk/release/phone-x86-release-unsigned-signed.apk

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Release signed APK
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.TOKEN }}"
            automatic_release_tag: "${{ steps.date.outputs.date }}"
            prerelease: false
            title: "Release-${{ steps.date.outputs.date }}"
            files: |
              ./app/phone/build/outputs/apk/release/phone-universal-release-unsigned-signed.apk
              ./app/phone/build/outputs/apk/release/phone-arm64-v8a-release-unsigned-signed.apk
              ./app/phone/build/outputs/apk/release/phone-armeabi-v7a-release-unsigned-signed.apk
              ./app/phone/build/outputs/apk/release/phone-x86_64-release-unsigned-signed.apk
              ./app/phone/build/outputs/apk/release/phone-x86-release-unsigned-signed.apk